FROM confluentinc/cp-server-connect-base:5.5.0
ARG CONNECTORS=""
RUN for c in ${CONNECTORS}; do confluent-hub install --no-prompt $c; done;

ENV CLASSPATH="${CLASSPATH}:/usr/share/java/custom-transforms/*"
