trigger:
- master

variables:Subscription not recognized.
  containerimagetag: '$(Build.SourceVersion)'
  containerregistry: 'nttcshowcase.azurecr.io'
  containerimagerepository: 'technologyconsulting-showcase-integrationdomain'
  containerregistrysericeconnection: 'acr-sc'

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: build
      displayName: Build App
      jobs:
        - job: getSecrets
            displayName: get Secrets and deploy
            steps:
              - task: AzureKeyVault@1
                inputs:
                  azureSubscription: 'Practice-Area-TC-Dev(95352c54-cee5-4d25-a9a1-0857616d97e5)'
                  KeyVaultName: 'vault-tc-showcase-prod'
                  SecretsFilter: '*'
                  RunAsPreJob: true
        - job: dockerbuild
            displayName: Docker Build and Push
            steps:
              - task: Docker@2
                inputs:
                  containerRegistry: $(containerregistrysericeconnection)
                  repository: $(containerimagerepository)
                  command: 'buildAndPush'
                  Dockerfile: '**/Dockerfile.connect'
                  tags: '$(containerimagetag)'
                  arguments: '--build-arg CONNECTORS="confluentinc/kafka-connect-jdbc:5.5.0 debezium/debezium-connector-postgresql:1.3.1"'

