# Tools required for deployment of app (Topics, Connectors and Ksql)
ARG VERSION_CONFLUENT
FROM confluentinc/cp-server:${VERSION_CONFLUENT}

RUN curl -Ls https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /usr/local/bin/jq \
    && chmod +x /usr/local/bin/jq