# Tools required for deployment of app (Topics, Connectors and Ksql)
ARG CPVERSION=""
FROM confluentinc/cp-server${CPVERSION}

RUN wget -Ls https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /usr/local/bin/jq
RUN chmod +x /usr/local/bin/jq
