on:
  push:
    branches:
      - master
      - deploy-debezium
env:
  containerimagetag: ${GITHUB_SHA}
  containerregistry: nttcshowcase.azurecr.io
  containerimagerepository: technologyconsulting-showcase-integrationdomain
  containerregistrysericeconnection: acr-sc

jobs:
  build_Stage_workerConfig:
    runs-on: ubuntu-latest
    name: edit worker-config
    steps:
      - run: |
          echo "config.providers.azure.param.azure.client.id=$CLIENT_ID" >> connect-worker.properties
          echo "config.providers.azure.param.azure.tenant.id=$TENANT_ID" >> connect-worker.properties
          echo "config.providers.azure.param.azure.secret.id=$SECRET_ID" >> connect-worker.properties
      - uses: pCYSl5EDgo/cat@master
        with:
          path: /resources/k8s/deployments/confluent-platform/connect-worker.properties
          shell: bash
        env:
          CLIENT_ID: ${{secrets.TC_SHOWCASE_ARM_CLIENT_ID}}
          TENANT_ID: ${{secrets.TC_SHOWCASE_ARM_TENANT_ID}}
          SECRET_ID: ${{secrets.TC_SHOWCASE_ARM_CLIENT_SECRET}}

  build_Stage_getKubeconfig:
    runs-on: ubuntu-latest
    name: get Kubeconfig and deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Kubeconfig
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          AKSRESOURCEGROUP: 'tc-showcase-test'
          AKSNAME: 'k8s-tc-showcase-test'
        working-directory: ./resources/pipelines/helperscripts
        run: |
            ./getKubeconfig.sh

  build_Stage_getSecrets:
    runs-on: ubuntu-latest
    name: get Secrets and deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get secrets
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
        working-directory: ./resources/pipelines/helperscripts
        run: |
          ./getKeyVaultSecrets.sh

  build_Stage_dockerbuild_connect:
    runs-on: ubuntu-latest
    name: Build and push Docker images Kafka Connect
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.TC_SHOWCASE_DOCKERHUB_USER }}
          password: ${{ secrets.TC_SHOWCASE_DOCKERHUB_PASSWORD }}
          dockerfile: ./resources/k8s/deployments/confluent-platform/Dockerfile.connect
          build-args: |
            CONNECTORS=confluentinc/kafka-connect-jdbc:5.5.0 debezium/debezium-connector-postgresql:1.3.1
          repository: novatec/technologyconsulting-showcase-integrationdomain
          tags: latest, ${{ env.SHORT_SHA }}
          tag_with_sha: true

  build_Stage_dockerbuild_configs:
    runs-on: ubuntu-latest
    name: Build and push Docker images Connector Configs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.TC_SHOWCASE_DOCKERHUB_USER }}
          password: ${{ secrets.TC_SHOWCASE_DOCKERHUB_PASSWORD }}
          dockerfile: ./resources/k8s/deployments/deploy/Dockerfile.deploy
          build-args: |
            CPVERSION="5.5.0"
          repository: novatec/technologyconsulting-showcase-integrationdomain
          tags: latest, ${{ env.SHORT_SHA }}
          tag_with_sha: true

  build_Stage_helm_deploy:
    runs-on: ubuntu-latest
    name: Helm install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via Helm
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          AKSRESOURCEGROUP: 'tc-showcase-test'
          AKSNAME: 'k8s-tc-showcase-test'
          IMAGETAG: ${{ env.SHORT_SHA }}
        run: |
          docker run \
            -v "$(pwd)/resources/k8s":/apps \
            -v "$(pwd)/resources/pipelines/helperscripts/kubeconfig":/root/.kube \
            alpine/helm \
                upgrade confluent-platform ./charts/confluent-platform $(for file in ./deployments/confluent-platform/*.yaml; do echo "--values $file"; done)

  #helm install confluent-platform ./charts/confluent-platform $(for file in ./deployments/confluent-platform/*.yaml; do echo "--values $file"; done)
